# vi: ft=terraform

variable "name" {
  type        = string
  description = "(Required) Prefix name for the Scope Map and Token resources."
}

variable "rg_name" {
  type        = string
  description = "(Required) Resource Group name."
}

variable "registry" {
  type        = string
  description = "(Required) Name of the Azure Container Registry."
}

variable "sc_description" {
  type        = string
  description = "(Optional) Brief description of the Scope Map object."
  default     = "Generated by Terraform."
}

variable "enable_token" {
  type        = bool
  description = "(Optional) Change this if you want to disable a token. Defaults to True."
  default     = true
}

variable "repository_access" {
  type        = list(string)
  description = "(Optional) The list of repositories that you want to include in your Scope Map. Admits wildcard. By default, allows pull permissions to all repositories within the registry."
  default     = ["repositories/*/content/read"]
}

